name: WakaTime Readme Update

on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          COMMIT_BY_ME: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
